services:
  kafka:
    image: apache/kafka:3.9.0-rc2
    container_name: kafka
    restart: unless-stopped
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS:
        BROKER://kafka:9092,
        CONTROLLER://kafka:9093,
        INTERNAL://kafka:29092
      KAFKA_ADVERTISED_LISTENERS:
        BROKER://localhost:9092,
        INTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        BROKER:PLAINTEXT,
        CONTROLLER:PLAINTEXT,
        INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

  redis:
    container_name: redis
    image: redis:7.4.1
    hostname: redis
    ports:
      - 6379:6379

volumes:
  kafka-data:
