spring:
  application:
    name: discussion
  cassandra:
    keyspace-name: distcomp
    local-datacenter: datacenter1
    schema-action: recreate_drop_unused
  datasource:
    url: jdbc:cassandra://localhost:9042/distcomp?localdatacenter=datacenter1
    hikari:
      minimum-idle: 2
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
  liquibase:
    enabled: true
    url: jdbc:cassandra://localhost:9042/distcomp?localdatacenter=datacenter1&compliancemode=Liquibase
    change-log: classpath:db/changelog/changelog-master.xml
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver

server:
  port: 24130
  servlet:
    context-path: /api/v1.0
