spring:
  application:
    name: discussion
  cassandra:
    keyspace-name: distcomp
    local-datacenter: datacenter1
    schema-action: recreate_drop_unused
  datasource:
    url: jdbc:cassandra://localhost:9042/distcomp?localdatacenter=datacenter1
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
    hikari:
      minimum-idle: 2
  liquibase:
    enabled: true
    url: jdbc:cassandra://localhost:9042/distcomp?localdatacenter=datacenter1&compliancemode=Liquibase
    change-log: classpath:db/changelog/changelog-master.xml
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: KafkaResponseTo:by.bsuir.discussion.kafka.dto.KafkaResponseTo
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: KafkaRequestTo:by.bsuir.discussion.kafka.dto.KafkaRequestTo
            trusted:
              packages: "*"

topic:
  tweet-note:
    request: InTopic
    response: OutTopic

server:
  port: 24130
  servlet:
    context-path: /api/v1.0
