spring:
  application:
    name: TaskNoSQL
  cassandra:
    keyspace-name: distcomp
    local-datacenter: datacenter1
  datasource:
    url: jdbc:cassandra://localhost:9042/distcomp?localdatacenter=datacenter1
    hikari:
      minimum-idle: 2
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 24130
  servlet:
    context-path: /api/v1.0
